import { chapterCode, moduleCode } from "./modules";

export const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

export const PDF = "application/pdf";
export const PPTX = "application/vnd.openxmlformats-officedocument.presentationml.presentation";
export const DOCX = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";

export type Citation = {
  n: number;
  chunk_id: number;
  doc_id: number;
  title: string;
  page: number;
  label: string | null;
  course: string | null;
  mime: string;
  path: string;
  snippet: string;
  text: string;
  /** read from an image by OCR; absent on answers saved before OCR existed */
  ocr?: boolean;
};

export type Done = {
  answer: string;
  citations: Citation[];
  citation_valid: boolean | null;
  log_id: number | null;
};

export type DocumentRow = {
  id: number;
  path: string;
  title: string;
  course: string | null;
  mime: string;
  page_count: number;
  status: "ok" | "empty_text" | "error";
  error: string | null;
  ingested_at: string;
  first_seen: string;
  chunk_count: number;
  /** generated by the local model after indexing; null until then or if it failed */
  summary: string | null;
  concepts: string[] | null;
  enrich_status: EnrichStatus;
  enrich_error: string | null;
  tags: Tag[];
};

export type Tag = { id: number; name: string };
export type TagRow = Tag & { course: string | null; count: number; raws: string[]; user_named: boolean };

export type EnrichStatus = "pending" | "ok" | "error" | "skipped";

export type EnrichmentStatus = {
  state: "running" | "waiting" | "paused" | "idle" | "waiting for Ollama" | "off";
  current: string | null;
  last_error: string | null;
  paused: boolean;
  enabled: boolean;
  counts: { ok: number; error: number; pending: number; skipped: number };
};

export type DocumentPages = Omit<DocumentRow, "chunk_count"> & {
  pages: { page: number; label: string | null; text: string }[];
};

export type Health = {
  ok: boolean;
  db: { ok: boolean; error?: string };
  ollama: { reachable: boolean; llm_model?: string; llm_pulled?: boolean; embed_pulled?: boolean; error?: string };
  blackboard_login_needed?: boolean;
};

type Locatable = { mime: string; page: number; label?: string | null };

/** Where in the file: "p. 3", "slide 3", a Word section heading, or "note". */
export function locator(c: Locatable): string {
  if (c.mime === PDF) return `p. ${c.page}`;
  if (c.mime === PPTX) return `slide ${c.page}`;
  return c.label ?? "note";
}

/** Library call number: PROB2 · CH1 · p. 3 */
export function callNumber(c: Locatable & { course: string | null; path: string }): string {
  const parts = [moduleCode(c.course), chapterCode(c.path)];
  if (c.mime === PDF || c.mime === PPTX || (c.mime === DOCX && c.label)) parts.push(locator(c));
  return parts.filter(Boolean).join(" · ");
}

/** "12 pages", "30 slides", "4 sections"; null for single-part notes. */
export function partsCount(mime: string, n: number): string | null {
  const unit = mime === PDF ? "page" : mime === PPTX ? "slide" : mime === DOCX ? "section" : null;
  return unit && `${n} ${unit}${n === 1 ? "" : "s"}`;
}

export function kindOf(mime: string): string {
  if (mime === PDF) return "PDF";
  if (mime === PPTX) return "Slides";
  if (mime === DOCX) return "Word";
  return "Note";
}

export function fileUrl(c: { doc_id: number; page?: number; mime: string }): string {
  const base = `${API_URL}/files/${c.doc_id}`;
  return c.mime === PDF && c.page ? `${base}#page=${c.page}` : base;
}

/** A PDF page rendered as an image: formulas survive, unlike the extracted text. */
export function pageImageUrl(docId: number, page: number): string {
  return `${API_URL}/documents/${docId}/pages/${page}.png`;
}

export function readerUrl(docId: number, page?: number): string {
  return `/documents/${docId}${page ? `#p-${page}` : ""}`;
}

type Handlers = {
  onToken: (text: string) => void;
  onDone: (done: Done) => void;
  onError: (message: string) => void;
};

/** POST /ask and parse the SSE stream (EventSource can't POST). */
export async function askStream(question: string, course: string | null, h: Handlers, signal?: AbortSignal) {
  let res: Response;
  try {
    res = await fetch(`${API_URL}/ask`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ question, course }),
      signal,
    });
  } catch {
    h.onError(`Can't reach the backend at ${API_URL}. Start it with: uv run uvicorn app.main:app`);
    return;
  }
  if (!res.ok || !res.body) {
    h.onError(`The backend answered ${res.status}. Check its log for the cause.`);
    return;
  }
  const reader = res.body.pipeThrough(new TextDecoderStream()).getReader();
  let buf = "";
  for (;;) {
    const { value, done } = await reader.read();
    if (done) break;
    buf += value;
    let sep: number;
    while ((sep = buf.indexOf("\n\n")) !== -1) {
      const block = buf.slice(0, sep);
      buf = buf.slice(sep + 2);
      const event = /^event: (.*)$/m.exec(block)?.[1];
      const data = /^data: (.*)$/m.exec(block)?.[1];
      if (!event || data === undefined) continue;
      const payload = JSON.parse(data);
      if (event === "token") h.onToken(payload.text);
      else if (event === "done") h.onDone(payload);
      else if (event === "error") h.onError(payload.message);
    }
  }
}

export async function getJSON<T>(path: string, signal?: AbortSignal): Promise<T> {
  const res = await fetch(`${API_URL}${path}`, { cache: "no-store", signal });
  if (!res.ok) throw new Error(`${path} returned ${res.status}`);
  return res.json();
}

/** One past question, as query_log stored it. answer is null if the stream failed before any text. */
export type HistoryItem = {
  id: number;
  ts: string;
  question: string;
  course: string | null;
  answer: string | null;
  citations: Citation[];
  citation_valid: boolean | null;
  latency_ms: number | null;
  /** your rating of the answer: 1 good, -1 wrong */
  feedback?: -1 | 1 | null;
  /** fiches you marked relevant (true) or not (false), by citation number */
  labels?: { relevant?: Record<string, boolean> } | null;
};

/** Rate an answer and/or mark fiches relevant; null clears. Omitted fields are left as they are. */
export function putLabels(
  id: number,
  body: { feedback?: -1 | 1 | null; relevant?: Record<string, boolean | null> },
): Promise<HistoryItem> {
  return sendJSON<HistoryItem>("PUT", `/history/${id}/labels`, body);
}

export function fetchHistory(
  opts: { course?: string | null; q?: string; before?: number; limit?: number },
  signal?: AbortSignal,
): Promise<HistoryItem[]> {
  const p = new URLSearchParams();
  if (opts.course) p.set("course", opts.course);
  if (opts.q) p.set("q", opts.q);
  if (opts.before !== undefined) p.set("before", String(opts.before));
  if (opts.limit !== undefined) p.set("limit", String(opts.limit));
  return getJSON<HistoryItem[]>(`/history?${p}`, signal);
}

export function fetchHistoryItem(id: number): Promise<HistoryItem> {
  return getJSON<HistoryItem>(`/history/${id}`);
}

/** Permanent. keepalive lets it finish while the page unloads. A 404 means it's already gone. */
export async function deleteHistory(id: number): Promise<boolean> {
  try {
    const res = await fetch(`${API_URL}/history/${id}`, { method: "DELETE", keepalive: true });
    return res.ok || res.status === 404;
  } catch {
    return false;
  }
}

export type AdminStatus = {
  services: { db: { ok: boolean; error?: string }; ollama: Health["ollama"] } | null;
  llm:
    | { loaded: false; model: string }
    | { loaded: true; model: string; gpu_share: number; expires_at: string | null }
    | null;
  gpu: { available: false } | { available: true; name: string; used_mib: number; total_mib: number };
  answers: { count: number; median_ms: number | null; max_ms: number | null; last_at: string | null } | null;
  index: {
    documents: number;
    chunks: number;
    excluded: number;
    db_bytes: number;
    ocr: { available: boolean; pages: number };
  } | null;
  backup: { name: string; at: string; bytes: number; kept: number } | null;
  enrichment: EnrichmentStatus | null;
};

export type AdminLibrary = {
  modules: { course: string | null; documents: number; chunks: number; problems: number }[];
  problems: {
    id: number;
    path: string;
    title: string;
    course: string | null;
    status: "empty_text" | "error";
    error: string | null;
  }[];
  excluded: { path: string; excluded_at: string; on_disk: boolean }[];
  summary_errors: { id: number; path: string; title: string; course: string | null; error: string | null }[];
};

/** An API error that keeps FastAPI's `detail` (a string, or a {field: reason} map for settings). */
export class ApiError extends Error {
  constructor(
    message: string,
    public status: number,
    public detail: unknown,
  ) {
    super(message);
  }
}

export async function sendJSON<T>(method: "POST" | "PUT" | "PATCH" | "DELETE", path: string, body: unknown): Promise<T> {
  let res: Response;
  try {
    res = await fetch(`${API_URL}${path}`, {
      method,
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
    });
  } catch {
    throw new ApiError(`Can't reach the backend at ${API_URL}.`, 0, null);
  }
  const data = await res.json().catch(() => null);
  if (!res.ok) {
    const detail = data?.detail;
    throw new ApiError(typeof detail === "string" ? detail : `${path} returned ${res.status}`, res.status, detail);
  }
  return data as T;
}

/** POST JSON; throws with the backend's `detail` so the UI can show why an action failed. */
export function postJSON<T>(path: string, body: unknown): Promise<T> {
  return sendJSON<T>("POST", path, body);
}

export type SettingRow = {
  key: string;
  label: string;
  value: string | number;
  source: "env" | "local" | "config" | "default";
  locked_by: string | null;
  editable: boolean;
  control: "int" | "float" | "choice" | "text";
  help: string;
  min: number | null;
  max: number | null;
  options: string[] | null;
};

export type SettingsView = {
  groups: { name: string; rows: SettingRow[] }[];
  readonly: { key: string; value: string; reason: string }[];
};

export type InsightsSummary = {
  questions: number;
  refused: number;
  invalid: number;
  failed: number;
  median_ms: number | null;
  max_ms: number | null;
  per_module: { course: string | null; questions: number; refused: number }[];
  per_day: { day: string; questions: number; median_ms: number | null }[];
};

export type ProblemRow = { id: number; ts: string; question: string; course: string | null; latency_ms: number | null };

export type ComparedHit = { chunk_id: number; title: string; page: number; label: string | null; score: number };
export type CompareResult = {
  summary: { questions: number; changed: number; flipped: number };
  rows: {
    question: string;
    course: string | null;
    dense: ComparedHit[];
    hybrid: ComparedHit[];
    verdict_dense: "answer" | "refuse";
    verdict_hybrid: "answer" | "refuse";
    changed: boolean;
  }[];
};

export type SyncEvent = { type: string; [k: string]: unknown };
export type SyncAction = "downloaded" | "saved_page" | "already_had" | "would_download" | "would_save_page" | "failed";
export type SyncJob = {
  id: number;
  mode: "sync" | "preview" | "probe" | "login";
  course: string | null;
  started_at: string;
  finished_at: string | null;
  state: "running" | "ok" | "login_required" | "failed" | "cancelled";
  exit_code: number | null;
  counts: Record<SyncAction, number>;
  bytes: number;
  error: string | null;
  events?: SyncEvent[];
  courses?: { name: string; folder: string | null }[] | null;
};
export type SyncStatus = {
  job: SyncJob | null;
  runs: SyncJob[];
  login_needed: boolean;
  last_full_sync: string | null;
  next_auto: string | null;
  auto_days: number;
  modules: string[];
};

export type EvalMode = "dense" | "hybrid";
export type EvalMetrics = {
  n: number;
  "recall@1"?: number;
  "recall@5"?: number;
  "recall@20"?: number;
  mrr?: number;
  refusal_rate?: number;
};
export type EvalSummary = {
  overall: Record<EvalMode, EvalMetrics>;
  by_course: Record<string, Record<EvalMode, EvalMetrics>>;
  by_lang: Record<string, Record<EvalMode, EvalMetrics>>;
  by_source: Record<string, Record<EvalMode, EvalMetrics>>;
  /** full runs only: answers generated with the current settings */
  answers?: {
    n: number;
    refusal_rate: number | null;
    citation_valid_rate: number | null;
    cited_right_rate: number | null;
    median_ms: number | null;
  };
};
export type EvalRun = {
  id: number;
  ts: string;
  kind: "retrieval" | "full";
  params: Record<string, string | number>;
  metrics: EvalSummary;
};
export type EvalJob = {
  kind: "generate" | "retrieval" | "full";
  state: "running" | "ok" | "failed" | "cancelled";
  done: number;
  total: number;
  error: string | null;
  result: { accepted?: number; rejected?: Record<string, number>; run_id?: number } | null;
};
export type EvalStatus = {
  questions: { generated: number; labelled: number };
  job: EvalJob | null;
  runs: EvalRun[];
  latest: EvalRun | null;
};
